FROM ubuntu:22

RUN wget https://dl.google.com/linux/linux_signing_key.pub  && \
    apt-key add linux_signing_key.pub && \
    echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list && \
    apt update && \
    apt install -y \
    python3-pip \
    python3-selenium \
    google-chrome-stable

