FROM ubuntu:22.04

# bashを使うためのおまじない
SHELL ["/bin/bash", "-c"]

# secret keyを読み込むためのやつ
ARG ACCOUNT_PW
ENV ACCOUNT_PW $ACCOUNT_PW
ARG EMAIL
ENV EMAIL $EMAIL
ARG MFA_KEY
ENV MFA_KEY $MFA_KEY
ARG URL
ENV URL $URL

# wgetとapt-key addをするための準備
RUN apt-get update && \
    apt-get install -y \
    wget \
    gnupg2

# chromeとselenium関連のインストール
RUN wget https://dl.google.com/linux/linux_signing_key.pub  && \
    apt-key add linux_signing_key.pub && \
    echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get install -y \
    python3-pip \
    python3-selenium \
    google-chrome-stable \
    # 日本語フォント
    fonts-ipafont-gothic

# chrome driver自動更新用のモジュール
RUN pip3 install webdriver-manager

RUN apt-get install -y \
    # 2段階認証コード生成
    oathtool

# 開発環境
RUN apt-get install -y \
    vim