name: Docker build
run-name: build
on:
  push:
    branches-ignore:
      - main

jobs:
  dev-image-build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # チェックアウト
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/848541161515/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-ci@site-autofill.iam.gserviceaccount.com'

    # gcloudの設定
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    # Docker に gcloud コマンドの Credential を使わせる
    - name: 'Configure docker to use the gcloud cli'
      run: gcloud auth configure-docker --quiet

    # Docker イメージを作成
    - name: 'Build a docker image'
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/test-image:${{ github.sha }}
        ACCOUNT_PW: ${{ secrets.ACCOUNT_PASS }}
        EMAIL: ${{ secrets.EMAIL }}
        MFA_KEY: ${{ secrets.MFA_KEY }}
        URL: ${{ secrets.URL }}
      run: docker build . -f ./DockerFile -t ${{ github.sha }} --build-arg ACCOUNT_PW=$ACCOUNT_PW --build-arg EMAIL=$EMAIL --build-arg MFA_KEY=$MFA_KEY --build-arg URL=$URL

    # Docker イメージを Container Registry に Push
    - name: 'Push the docker image to Container Registry'
      run: docker push $IMAGE
# on:
#   TODO:ここにmargeされたときの処理を書く