name: Docker build
run-name: build
on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: "write"
      id-token: "write"

    steps:
      # チェックアウト
      - uses: "actions/checkout@v3"
        env:
          ACCOUNT_PW: ${{ secrets.ACCOUNT_PASS }}
          EMAIL: ${{ secrets.EMAIL }}
          MFA_KEY: ${{ secrets.MFA_KEY }}
          URL: ${{ secrets.URL }}

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          # yamllint disable-line rule:line-length
          workload_identity_provider: "projects/848541161515/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-ci@site-autofill.iam.gserviceaccount.com"

      # # yamllint
      # - name: Yamllint Github Action
      #   uses: karancode/yamllint-github-action@v2.0.0

      # - name: export credentials
      #   run: echo "${{ secrets.GCP_SA }}" > credential.json

      # Docker に gcloud コマンドの Credential を使わせる
      - name: "Configure docker to use the gcloud cli"
        run: >
          echo "${{ secrets.GCP_SA }}" > credential.json &&
          ls -la &&
          gcloud auth activate-service-account "github-ci@site-autofill.iam.gserviceaccount.com" --key-file=credential.json &&
          gcloud auth list

      # # Docker イメージを作成
      # - name: "Build a docker image"
      #   if: github.ref != 'refs/heads/main'
      #   run: >
      #     docker build -f ./DockerFile -t
      #     asia.gcr.io/site-autofill/staging:latest .
      #     --build-arg ACCOUNT_PW=$ACCOUNT_PW
      #     --build-arg EMAIL=$EMAIL
      #     --build-arg MFA_KEY=$MFA_KEY
      #     --build-arg URL=$URL

      # # Docker イメージを Container Registry に Push
      # - name: "Push the docker image to Container Registry"
      #   if: github.ref != 'refs/heads/main'
      #   run: docker push asia.gcr.io/site-autofill/staging:latest

      # # Docker イメージをコピー
      # - name: "Image copy from stg"
      #   if: github.ref == 'refs/heads/main'
      #   run: >
      #     gcloud container images add-tag
      #     asia.gcr.io/site-autofill/staging:latest
      #     asia.gcr.io/site-autofill/production:latest
